#print('im alfat taufik \nwho are ya') enter tanpa enter
name = 'nazwa'
#print(len(name))
#print(name[4])
print(name.index("z"))
print(name.replace('n', 'N'))
print(name.upper())
print(type(1))
print(type(1.4))
print(type("anjing"))
print(type("4j"))
print(type(True))
print(type(False))
print(type([1, 2, 3]))
print(type({"satu" : 1}))
print(type({3.2, 2, 9}))
print(type(("tuple", "tidak")))